config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :tweets
  get 'top/main'
  post 'top/login'
  get 'top/logout'
  resources :likes
  root 'tweets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :message, presence: true
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  
  def like(user)
    likes.create(user_id: user.id)
  end

  def unlike(user)
    likes.find_by(user_id: user.id).destroy
  end

  def liked?(user) #いいね済みか調べる(true / false)
    like_users.include?(user)
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :uid, uniqueness: true
  validates :password, presence: true, confirmation: true
  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_tweets, through: :likes, source: :tweet
  
  attr_accessor :password, :password_confirmation

  def password=(val)
   if val.present?
      self.pass = BCrypt::Password.create(val)
   end
   @password = val
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
private
    def current_user
        if session[:login_uid]
            User.find_by(uid: session[:login_uid])
        end
    end
    helper_method :current_user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create 
    tweet = Tweet.find(params[:tweet_id])
    unless tweet.liked?(current_user)
      tweeet.like(current_user)
    end
    redirect_to root_path
  end

  def destroy
    tweet = Tweet.find(params[:id])
    if tweet.liked?(current_user)
      tweeet.unlike(current_user)
    end
    redirect_to root_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    render 'login'
  end

  def login
    user = User.find_by(uid: params[:uid])
    if user and BCrypt::Password.new(user.pass) == params[:pass]
      flash[:notice] = 'ログインしました'
      session[:login_uid] = user.uid
      redirect_to root_path
    else
      flash[:notice] = 'ログインエラー'
      render 'login'
    end
  end

  def logout
   flash[:notice] = 'ログアウトしました'
    session.delete(:login_uid)
    redirect_to root_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end

  def create
    #ログイン中にしたツイートリンクが表示されないのでsession[:user_id]が空であることは考慮しなくてよい
    user = User.find_by(uid: current_user.uid)
    @tweet = Tweet.new(message: params[:tweet][:message], user_id: user.id)
    if @tweet.save
       flash[:notice] = 'ツイートしました'
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create 
    @user = User.new(uid: params[:user][:uid], 
    password: params[:user][:password],
    password_confirmation: params[:user][:password_confirmation])
    if @user.valid? #validatesを実行してくれる
      flash[:notice] = 'userを追加しました'
      @user.pass = BCrypt::Password.create(params[:user][:password])
      @user.save
      redirect_to users_path
    else
      render 'new'
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L5</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <p>
    <% if current_user %>
      ログイン中（<%= current_user.uid %>さん）
    <% else %>
      ログインしていません
    <% end %>
    </p>
  </body>
</html>

app/views/top/login.html.erb
<%= form_tag top_login_path, method: :post do %>
  <%= label_tag :uid, 'uid' %> 
  <%= text_field_tag :uid %> 
  <%= label_tag :pass, 'pass' %> 
  <%= password_field_tag :pass %> 
  <%= submit_tag 'ログイン' %>
<% end %>

app/views/tweets/index.html.erb
<% @tweets.each do |e| %>
  <p>
    <%= e.message %>
    <% if current_user %>
      <%= link_to '削除', tweet_path(e), method: :delete %>
      <% if e.likes.count > 0 %>
        <%= link_to 'いいね削除', like_path(e), method: :delete %>
      <% else %>
        <%= link_to 'いいね', likes_path(tweet_id: e.id), method: :post %>
      <% end %>
    <% end %>
    </p>
<% end %>

<p> 
<% if current_user %>
  <%= link_to 'ツイートする', new_tweet_path %>
<% end %>
</p>

<p>
<% if current_user %>
  <%= link_to 'ログアウト', top_logout_path %>
<% else %>
  <%= link_to 'ログイン', top_main_path %>
<% end %>
</p>

<p>
  <%= link_to 'ユーザ一覧', users_path %>
</p>

app/views/tweets/new.html.erb
<%= form_for @tweet, url: {action: :create} do |f| %>
  <%= f.label :message, 'message' %> 
  <%= f.text_field :message %> 
  <%= f.submit 'ツイートする' %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |e| %>
  <p>
    <%= e.uid %>
    <%= e.pass %>
    <%= link_to '削除', user_path(e), method: :delete %>
    </p>
<% end %>

<p>
  <%= link_to '新規ユーザ追加', new_user_path %>
</p>

<p>
  <%= link_to 'ツイート一覧', tweets_path %>
</p>

app/views/users/new.html.erb
<% if @user.errors.present? %>
    <span style="color:red;">
        <h3>エラーがあります。</h3>
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </span>
<% end %>

<%= form_for @user, url: {action: :create} do |f| %>
  <%= f.label :uid, 'uid' %> 
  <%= f.text_field :uid %> 
  <%= f.label :password, 'password' %> 
  <%= f.password_field :password %> 
  <%= f.label :password_confirmation, 'password(確認)' %> 
  <%= f.password_field :password_confirmation %>
  <%= f.submit '登録' %>
<% end %>